baseURL = "https://rajputshamshed-ux.github.io/"
languageCode = "fr-fr"
title = "RajputShamshed UX"
theme = "PaperMod"

[params]
    env = "production"
    title = "RajputShamshed UX"
    description = "Hub de conformite GRC et Cybersecurity"
    defaultTheme = "dark"
    showCodeCopyButtons = true

    [params.homeInfoParams]
        Title = "Bienvenue sur Cyber Hub"
        Content = "Analyses de conformite PCI-DSS, ISO 27001 et fiches techniques."

[[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 10

[[menu.main]]
    name = "Cheatsheets"
    url = "/cheatsheets/"
    weight = 20

[[menu.main]]
    name = "Admin"
    url = "/admin/"
    weight = 30
